# Generated by Django 4.1.1 on 2022-09-06 04:44

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("short_name", models.CharField(max_length=200)),
                ("position", models.CharField(max_length=200)),
                ("age", models.CharField(max_length=200)),
                ("height", models.IntegerField(default=0)),
                ("weight", models.IntegerField(default=0)),
                ("height_diff", models.IntegerField(default=0)),
                ("weight_diff", models.IntegerField(default=0)),
                ("attributes", models.CharField(max_length=200)),
                ("youtube1_title", models.CharField(max_length=200)),
                ("youtube1_image", models.CharField(max_length=200)),
                ("youtube1_url", models.CharField(max_length=200)),
                ("youtube2_title", models.CharField(max_length=200)),
                ("youtube2_image", models.CharField(max_length=200)),
                ("youtube2_url", models.CharField(max_length=200)),
                ("youtube3_title", models.CharField(max_length=200)),
                ("youtube3_image", models.CharField(max_length=200)),
                ("youtube3_url", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Question",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("question_text", models.CharField(max_length=200)),
                ("pub_date", models.DateTimeField(verbose_name="date published")),
            ],
        ),
        migrations.CreateModel(
            name="user_data",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("age", models.CharField(max_length=200)),
                ("male_height", models.IntegerField(default=0)),
                ("male_weight", models.IntegerField(default=0)),
                ("female_height", models.IntegerField(default=0)),
                ("female_weight", models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="UserInput",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("height", models.IntegerField(default=0, verbose_name="身長")),
                ("weight", models.IntegerField(default=0, verbose_name="体重")),
                (
                    "age",
                    models.CharField(blank=True, max_length=200, verbose_name="年齢"),
                ),
                (
                    "position",
                    models.CharField(blank=True, max_length=200, verbose_name="ポジション"),
                ),
                (
                    "attributes",
                    models.CharField(blank=True, max_length=200, verbose_name="特徴"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Choice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("choice_text", models.CharField(max_length=200)),
                ("votes", models.IntegerField(default=0)),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="app.question"
                    ),
                ),
            ],
        ),
    ]
