# Generated by Django 4.1.1 on 2022-09-08 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="choice",
            name="question",
        ),
        migrations.DeleteModel(
            name="UserInput",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="youtube1_image",
            new_name="foot",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="youtube1_title",
            new_name="image",
        ),
        migrations.RenameField(
            model_name="data",
            old_name="youtube1_url",
            new_name="video",
        ),
        migrations.RemoveField(
            model_name="data",
            name="youtube2_image",
        ),
        migrations.RemoveField(
            model_name="data",
            name="youtube2_title",
        ),
        migrations.RemoveField(
            model_name="data",
            name="youtube2_url",
        ),
        migrations.RemoveField(
            model_name="data",
            name="youtube3_image",
        ),
        migrations.RemoveField(
            model_name="data",
            name="youtube3_title",
        ),
        migrations.RemoveField(
            model_name="data",
            name="youtube3_url",
        ),
        migrations.DeleteModel(
            name="Choice",
        ),
        migrations.DeleteModel(
            name="Question",
        ),
    ]
