# Generated by Django 3.2.15 on 2022-09-05 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('short_name', models.CharField(max_length=200)),
                ('position', models.CharField(max_length=200)),
                ('age', models.IntegerField(default=0)),
                ('height', models.IntegerField(default=0)),
                ('height_diff', models.IntegerField(default=0)),
                ('weight_diff', models.IntegerField(default=0)),
                ('attributes', models.CharField(max_length=200)),
                ('youtube1_title', models.CharField(max_length=200)),
                ('youtube1_image', models.CharField(max_length=200)),
                ('youtube1_url', models.CharField(max_length=200)),
                ('youtube2_title', models.CharField(max_length=200)),
                ('youtube2_image', models.CharField(max_length=200)),
                ('youtube2_url', models.CharField(max_length=200)),
                ('youtube3_title', models.CharField(max_length=200)),
                ('youtube3_image', models.CharField(max_length=200)),
                ('youtube3_url', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='user_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(default=0)),
                ('male_height', models.IntegerField(default=0)),
                ('male_weight', models.IntegerField(default=0)),
                ('female_height', models.IntegerField(default=0)),
                ('female_weight', models.IntegerField(default=0)),
            ],
        ),
    ]
