# Generated by Django 3.2.15 on 2022-09-05 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_data_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='data',
            name='weight',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='age',
            field=models.CharField(max_length=200),
        ),
    ]
